export const DUMMY_MINES = [
  {
    id: 1,
    action: "+",
    quantity: 10,
    turned: false,
    audio: "/assets/sounds/sparkleFx.mp3",
  },
  {
    id: 2,
    action: "+",
    quantity: 20,
    turned: false,
    audio: "/assets/sounds/sparkleFx.mp3",
  },
  {
    id: 3,
    action: "+",
    quantity: 15,
    turned: false,
    audio: "/assets/sounds/sparkleFx.mp3",
  },
  {
    id: 4,
    action: "+",
    quantity: 50,
    turned: false,
    audio: "/assets/sounds/sparkleFx.mp3",
  },
  {
    id: 5,
    action: "-",
    quantity: 10,
    turned: false,
    audio: "/assets/sounds/sweepFx.mp3",
  },
  {
    id: 6,
    action: "-",
    quantity: 20,
    turned: false,
    audio: "/assets/sounds/sweepFx.mp3",
  },
  {
    id: 7,
    action: "-",
    quantity: 15,
    turned: false,
    audio: "/assets/sounds/sweepFx.mp3",
  },
  {
    id: 8,
    action: "-",
    quantity: 50,
    turned: false,
    audio: "/assets/sounds/sweepFx.mp3",
  },
  {
    id: 9,
    action: "+",
    quantity: 100,
    turned: false,
    audio: "/assets/sounds/sparkleFx.mp3",
  },
  {
    id: 10,
    action: "+",
    quantity: 50,
    turned: false,
    audio: "/assets/sounds/sparkleFx.mp3",
  },
  {
    id: 11,
    action: "+",
    quantity: 30,
    turned: false,
    audio: "/assets/sounds/sparkleFx.mp3",
  },
  {
    id: 12,
    action: "+",
    quantity: 150,
    turned: false,
    audio: "/assets/sounds/sparkleFx.mp3",
  },
  {
    id: 13,
    action: "-",
    quantity: 100,
    turned: false,
    audio: "/assets/sounds/sweepFx.mp3",
  },
  {
    id: 14,
    action: "-",
    quantity: 10,
    turned: false,
    audio: "/assets/sounds/sweepFx.mp3",
  },
  {
    id: 15,
    action: "Switch!",
    turned: false,
    audio: "/assets/sounds/switchFx.mp3",
  },
  {
    id: 16,
    action: "Boom!",
    turned: false,
    audio: "/assets/sounds/explodeFx.mp3",
  },
  {
    id: 17,
    action: "x",
    quantity: 2,
    turned: false,
    audio: "/assets/sounds/multiplyFx.mp3",
  },
  {
    id: 18,
    action: "x",
    quantity: 3,
    turned: false,
    audio: "/assets/sounds/multiplyFx.mp3",
  },
  {
    id: 19,
    action: "x",
    quantity: 2,
    turned: false,
    audio: "/assets/sounds/multiplyFx.mp3",
  },
  {
    id: 20,
    action: "x",
    quantity: 2,
    turned: false,
    audio: "/assets/sounds/multiplyFx.mp3",
  },
];
